### ISSUE TITLE
Fix the Modal Form

### ISSUE THREAD

**Issue by MarcoMorawec** [MMalmfeldt/malmy#2]
On your modal a few buttons are outside of the actual modal. 

Can you put those buttons inside of your modal. 

![screen shot 2015-04-13 at 11 48 04 am](https://cloud.githubusercontent.com/assets/1474717/7119400/553de8e8-e1d3-11e4-9e9d-62c2b95c4ac0.png)

**Sidenote**: I'm not sure if a user would understand the difference between the "create" and "save changes" button.

**Comment by MMalmfeldt** [comment]
I fixed these issues. Thanks, Marco.
